[tool.poetry]
name = "nlp"
version = "0.1.0"
description = ""
authors = ["BenG <j.j.goldberger@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastai = "^2.7.16"
jupyter = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
